### ISSUE TITLE
Add option to change the number of game-seconds that .slp files are filtered by

### ISSUE THREAD

**Issue by kleutzinger** [project-slippi/slippi-desktop-app#78]
Right now the browser always filters games shorter than 30sec. This value ought be modifiable. Perhaps something interesting happened during a quick handwarmer.  
I tried implementing it myself, but I have no idea how react works, to be honest.  
https://github.com/kleutzinger/slippi-desktop-app/commit/5867ec5be334823295ee5422dc260a81eeebaf13  
the form to modify the value is mostly nonfuctional/wrong, but other two files are probably close.  

![Plj0VB5](https://user-images.githubusercontent.com/6435727/87239993-161c8780-c3ca-11ea-8a03-516246a4da0a.png)

**Comment by JLaferri** [comment]
This is not a configuration option I'm interested in adding. If anything there should be a link button on the notif that says replays have been filtered that allows them to be shown. I prefer not adding configuration options if possible because it can lead to confusing UI as you make more and more things configurable

**Comment by kleutzinger** [comment]
I'd argue that making user data inaccessible based off an arbitrary number ought to be at least toggle-able. However, I agree that an "undo filter" would be sufficient.

I once was trying to locate the .slp file where my opponent quit out after a funny rest at about 10 seconds into the game, and had a hard time.
